MangoWeb/Models/CouponDto.cs
namespace MangoWeb.Models
{
    public class CouponDto
    {
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public double DiscountAmount { get; set; }
        public int MinAmount { get; set; }
    }
}

MangoWeb/Models/ErrorViewModel.cs
namespace MangoWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MangoWeb/Models/RequestDto.cs
using static MangoWeb.Utility.SD;

namespace MangoWeb.Models
{
    public class RequestDto
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
        public string AccessToken { get; set; }

    }
}

MangoWeb/Models/ResponseDto.cs
namespace MangoWeb.Models
{
    public class ResponseDto
    {
        public object? Result { get; set; }
        public bool IsSuccess { get; set; } = true;
        public string Message { get; set; } = "";

    }
}

MangoWeb/Controllers/CouponController.cs
using MangoWeb.Models;
using MangoWeb.Services.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Reflection;

namespace MangoWeb.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }
        public async Task<IActionResult> CouponIndex()
        {
            List<CouponDto>? list = new();
            ResponseDto? response = await _couponService.GetAllCouponsAsync();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(response.Result));

            }
            else
            {
                TempData["error"] = response?.Message;
            }

            return View(list);
        }

        public async  Task<IActionResult> CouponCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CouponCreate(CouponDto model)
        {

            if (ModelState.IsValid)
            {
                ResponseDto? response = await _couponService.CreateCouponAsync(model);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Coupon created successfully";
                    return RedirectToAction(nameof(CouponIndex)) ;
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CouponDelete([FromBody] int id)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? response = await _couponService.DeleteCouponAsync(id);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Coupon deleted successfully";
                    return RedirectToAction(nameof(CouponIndex));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return NotFound();
        }
    }
}

MangoWeb/Controllers/HomeController.cs
using MangoWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MangoWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MangoWeb/Views/Coupon/CouponCreate.cshtml
@model CouponDto
<form asp-action="CouponCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Create Coupon</h1>

        <hr />
        <div class="row">
            <div class="col-2">
                <label  class="control-label pt-2" style="font-size:20px;">Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CouponCode"  class="form-control" />
                <span class="text-danger" asp-validation-for="CouponCode"></span>
            </div>
            <div class="col-2">
                <label  class="control-label pt-2" style="font-size:20px;">Discount Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="DiscountAmount" class="form-control" />
                <span class="text-danger" asp-validation-for="DiscountAmount"></span>
            </div>
            <div class="col-2">
                <label  class="control-label pt-2" style="font-size:20px;">Min Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="MinAmount" class="form-control" />
                <span class="text-danger" asp-validation-for="MinAmount"></span>

            </div>
            
            <div class="col-5 offset-2">

                <a asp-action="CouponIndex"  class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />

            </div>

        </div>

        <div>
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
 }

MangoWeb/Views/Coupon/CouponIndex.cshtml
@model IEnumerable<CouponDto>

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white">Coupons List</h1>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Coupon" asp-action="CouponCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Create New Coupon</a>

            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Coupon Code
                    </th>
                    <th>
                        Discount Amount
                    </th>
                    <th>
                        Minimum Amount
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @item.CouponCode
                        </td>
                        <td>
                            @((item.DiscountAmount).ToString("c"))
                        </td>
                        <td>
                            @((item.MinAmount).ToString("c"))
                        </td>
                        <td>
                            <button data-id="@item.CouponId"   class="deleteButton btn btn-danger">
                                <i class="bi bi-trash"></i>
                            </button>
                        </td>
                    </tr>

                }


            </tbody>
        </table>

    </div>

</div>

@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>


        <script>
            document.addEventListener('DOMContentLoaded', function () {

            $(document).on('click', '.deleteButton', (e) => {
                    var itemId = $(e.currentTarget).data('id');
                    console.log(itemId)
                    Swal.fire({
                        title: 'Are you sure?',
                        text: 'You are about to delete this item.',
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes, delete it!'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            fetch('/Coupon/CouponDelete', {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json'
                                },
                                body: JSON.stringify(itemId)
                        })
                                .then(response => {
                                    if (response.ok) {
                                    location.href = '/Coupon/CouponIndex'
                                    } else {
                                    Swal.fire('Failed to delete item', '', 'info')
                                    }
                                })
                                .catch(error => {
                                    console.error('Error deleting item:', error);
                                });
                        }
                    });
                });
            });
    </script>

}

MangoWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MangoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MangoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MangoWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MangoWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications"/>
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="text-center">
            Minaya Aliyeva(Farzali) made with love <i class="bi bi-balloon-heart-fill"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MangoWeb/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"> </script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}


@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"> </script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}